Update pipeline-devsecops.yml

diff --git a/.github/workflows/pipeline-devsecops.yml b/.github/workflows/pipeline-devsecops.yml
--- a/.github/workflows/pipeline-devsecops.yml
+++ b/.github/workflows/pipeline-devsecops.yml
@@ -23,6 +23,33 @@ jobs:
     - name: Build
       run: npm run build
 
+    - name: Validando existencia de proyecto en SonarCloud
+      id: validateProjectOnSonar
+      run: |
+        set +e
+        response=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.SONAR_TOKEN }}:" \
+          -X POST "https://sonarcloud.io/api/projects/create" \
+          -d "name=${{ github.event.repository.name }}" \
+          -d "project=${{ github.event.repository.name }}" \
+          -d "organization=devsecops" \
+          -d "visibility=public")
+
+        if [ "$response" -eq 403 ]; then
+          echo "Autenticación fallida o permisos insuficientes para crear el proyecto en SonarCloud"
+          exit 1
+        elif [ "$response" -ne 200 ] && [ "$response" -ne 201 ]; then
+          echo "Error al crear el proyecto en SonarCloud: Código de respuesta $response"
+          exit 1
+        else
+          echo "Proyecto ${{ github.event.repository.name }} fue creado exitosamente en SonarCloud"
+          echo "Se establece rama main como rama por defecto"
+          curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
+            -X POST "https://sonarcloud.io/api/project_branches/rename" \
+            -d "name=main" \
+            -d "project=${{ github.event.repository.name }}"
+        fi
+
+
     - name: Install jq
       run: sudo apt-get install -y jq
 
@@ -49,19 +76,7 @@ jobs:
         fi
 
 
-    - name: Validando existencia de proyecto en SonarCloud
-      id: validateProjectOnSonar
-      run: |
-        set +e
-        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecops' -d 'visibility=public'
-        if [ $? -ne 0 ]
-        then
-          echo "Proyecto ya existe en Sonarcloud"
-        else
-          echo "Proyecto ${{ github.event.repository.name }} fue creado exitosamente en SonarCloud"
-          echo "Se establece rama main como rama por defecto"
-          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main'  -d 'project=${{ github.event.repository.name }}'
-        fi
+
         
 
 
